apiVersion: v1
kind: ConfigMap
metadata:
  name: es-configmap
  namespace: {{ .Release.Namespace }}
data:
  elasticsearch.yml: |
{{ include (print .Template.BasePath "/tpl/_elasticsearch.yml.tpl") . | indent 2 }}
{{ include (print .Template.BasePath "/tpl/_azure_storage.yml.tpl") . | indent 2 }}
