apiVersion: v1
kind: ConfigMap
metadata:
  name: es-configmap
  namespace: {{ .Release.Namespace }}
data:
  elasticsearch.yml: |
{{ include (print .Template.BasePath "/config/_elasticsearch.yaml") . | indent 4 }}
{{ include (print .Template.BasePath "/config/_azure_storage.yaml") . | indent 4 }}
