{{- if .Values.curator.install -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config-configmap
  namespace: {{ .Release.Namespace }}
data:
  curator.yml: |
    client:
      hosts:
        - elasticsearch
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      aws_key:
      aws_secret_key:
      aws_region:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
{{- end -}}
