kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: logstash-managedfast
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
reclaimPolicy: Retain
