{{- if .Values.templates.install -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: templates-configmap
  namespace: {{ .Release.Namespace }}
  annotations:
    config/checksum: {{ print .Values.templates | sha256sum }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  templates.json: |
{{ include (print .Template.BasePath "/tpl/_templates.json.tpl") . | indent 4 }}
{{- end -}}
